name: Build and Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust this version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install the dependencies from the requirements.txt

    - name: Run tests (optional, but recommended)
      run: |
        # Add your test script here (if you have any tests to run)
        echo "No tests added" 

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appbyyash'  # Replace with your Azure Web App name
        slot-name: 'production'  # Optional: If you have deployment slots, use this field
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # The publish profile stored in GitHub secrets
